name: Add Post

on:
  repository_dispatch:
    types: [add_post]

jobs:
  add_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create posts.json if not exists
        run: |
          if [ ! -f posts.json ]; then
            echo "[]" > posts.json
          fi

      - name: Add new post
        run: |
          node api/add_post.js '${{ github.event.client_payload.name }}' '${{ github.event.client_payload.message }}'

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add posts.json
          git commit -m "Add post"
          git push
